export const teamNames1 = ["Annihilators",
"Avengers",
"Bad to The Bone",
"Panthers",
"Black Widows",
"Blitzkrieg",
"Braindead Zombies",
"Brewmaster Crew",
"Brute Force",
"Butchers",
"Chaos",
"Chargers",
"Chernobyl",
"Collision Course",
"Deathwish",
"Defenders",
"Demolition Crew",
"Desert Storm",
"Divide and Conquer",
"Dominators",
"Dropping Bombs",
"End Game",
"Enforcers",
"Fire Starters",
"Gargoyles",
"Gatling Guns",
"Ghost Riders",
"Gorillas In the Mist",
"Grave Diggers",
"Gunners",
"Guns for Hire",
"Hammerheads",
"Hell’s Angels",
"Hellraisers",
"High-Voltage",
"Insurgents",
"Jawbreakers",
"Justice Bringers",
"Lethal",
"Little Boy",
"Mean Machine",
"Mercenaries",
"Mud Dogs",
"Mutiny",
"Neck Breakers",
"Nemesis",
"No Fear",
"No Rules",
"No Sympathy",
"One Shot Killers"
];

export const teamNames2 = ["Pulverizers",
"Rage",
"Raging Bulls",
"Rhinos",
"Savages",
"Shock and Awe",
"Skull Crushers",
"Slayers",
"Soldiers",
"Soul Takers",
"Speed Demons",
"Stone Crushers",
"Street-sweepers",
"Tech Warriors",
"Terminators",
"Terrorizers",
"The Arsenal",
"The Badasses",
"The Bane of Your Existence",
"The Barbarians",
"The Blazers",
"The Bulldogs",
"The Demented",
"The Enemy",
"The Fighting Irish",
"The Firing Squad",
"The Four Horsemen of The Apocalypse",
"The Frontline",
"The Hit List",
"The House Thrashers",
"The Intimidators",
"The Mean Ones",
"The Mongolians",
"The Outlaws",
"The Pitbulls",
"The Punishers",
"The Reapers",
"The Rebellion",
"The Security",
"The Storm Bringers",
"The Tribe",
"The Unredeemable",
"Trigger Happy",
"Vandals",
"Veterans",
"Vigilantes",
"Viking Raiders",
"Warmongers",
"Weapons of Mass Destruction",
"Your Worst Nightmare"];